/**
 * Cross-person relationships for the Sanguo example.
 *
 * These are explicit, human-confirmed connections — the opposite of the
 * machine-suggested similarity edges. They are persisted as `CavinEdge`
 * entries and drawn on the canvas as solid lines.
 *
 * The `parentId` tree already covers family/succession, so this list focuses
 * on the meaningful political/military/personal links: 君臣、同僚、师徒、
 * 对手、盟友、旧友、不和 etc.
 */

export interface SanguoRelation {
  from: string
  to: string
  type: string
  note?: string
}

export interface SanguoEdge {
  id: string
  from: string
  to: string
  createdAt: number
  /** Human-readable relation label, e.g. "主公" / "师徒". */
  label?: string
}

export const RELATIONS: SanguoRelation[] = [
  { from: 'liu-bei', to: 'zhuge-liang', type: '三顾茅庐 · 君臣' },
  { from: 'liu-bei', to: 'guan-yu', type: '义兄弟 · 君臣' },
  { from: 'liu-bei', to: 'zhang-fei', type: '义兄弟 · 君臣' },
  { from: 'liu-bei', to: 'zhao-yun', type: '君臣 · 护卫' },
  { from: 'liu-bei', to: 'ma-chao', type: '君臣' },
  { from: 'liu-bei', to: 'huang-zhong', type: '君臣' },
  { from: 'liu-bei', to: 'fa-zheng', type: '谋主 · 君臣' },
  { from: 'liu-bei', to: 'pang-tong', type: '谋主 · 君臣' },
  { from: 'liu-bei', to: 'mi-zhu', type: '元从 · 资助' },
  { from: 'liu-bei', to: 'sun-qian', type: '元从 · 幕僚' },
  { from: 'liu-bei', to: 'jian-yong', type: '元从 · 故交' },
  { from: 'liu-bei', to: 'liu-zhang', type: '同宗 · 取益州' },
  { from: 'liu-bei', to: 'cao-cao', type: '青梅煮酒 · 对手' },
  { from: 'liu-bei', to: 'sun-quan', type: '盟友 · 联姻' },
  { from: 'guan-yu', to: 'zhang-fei', type: '义兄弟' },
  { from: 'guan-yu', to: 'zhao-yun', type: '同僚' },
  { from: 'guan-yu', to: 'huang-zhong', type: '同僚' },
  { from: 'guan-yu', to: 'cao-cao', type: '知遇 · 敬重' },
  { from: 'guan-yu', to: 'lv-meng', type: '对手 · 白衣渡江' },
  { from: 'guan-yu', to: 'sun-quan', type: '对手' },
  { from: 'guan-yu', to: 'zhang-liao', type: '旧友 · 同乡' },
  { from: 'zhang-fei', to: 'zhao-yun', type: '同僚' },
  { from: 'zhang-fei', to: 'yan-yan', type: '义释 · 收降' },
  { from: 'zhao-yun', to: 'zhuge-liang', type: '君臣 · 同僚' },
  { from: 'ma-chao', to: 'ma-dai', type: '从兄弟' },
  { from: 'zhuge-liang', to: 'pang-tong', type: '卧龙凤雏 · 同僚' },
  { from: 'zhuge-liang', to: 'fa-zheng', type: '同僚' },
  { from: 'zhuge-liang', to: 'jiang-wei', type: '师徒 · 传人' },
  { from: 'zhuge-liang', to: 'ma-su', type: '赏识 · 街亭之失' },
  { from: 'zhuge-liang', to: 'jiang-wan', type: '举荐 · 继任' },
  { from: 'zhuge-liang', to: 'fei-yi', type: '举荐 · 继任' },
  { from: 'zhuge-liang', to: 'dong-yun', type: '举荐' },
  { from: 'zhuge-liang', to: 'wei-yan', type: '部下 · 猜疑' },
  { from: 'zhuge-liang', to: 'sima-yi', type: '宿敌 · 五丈原' },
  { from: 'pang-tong', to: 'zhang-ren', type: '对手 · 落凤坡' },
  { from: 'fa-zheng', to: 'huang-zhong', type: '定军山献策' },
  { from: 'ma-su', to: 'zhang-he', type: '对手 · 街亭' },
  { from: 'wei-yan', to: 'yang-yi', type: '不和 · 争权' },
  { from: 'zhang-fei', to: 'zhang-bao', type: '父子' },
  { from: 'zhao-yun', to: 'zhao-tong', type: '父子' },
  { from: 'zhao-yun', to: 'zhao-guang', type: '父子' },
  { from: 'cao-cao', to: 'xun-yu', type: '王佐 · 谋主' },
  { from: 'cao-cao', to: 'xun-you', type: '谋主' },
  { from: 'cao-cao', to: 'guo-jia', type: '谋主 · 奇佐' },
  { from: 'cao-cao', to: 'jia-xu', type: '谋主 · 毒士' },
  { from: 'cao-cao', to: 'cheng-yu', type: '谋臣' },
  { from: 'cao-cao', to: 'liu-ye', type: '谋臣' },
  { from: 'cao-cao', to: 'sima-yi', type: '君臣 · 猜忌' },
  { from: 'cao-cao', to: 'zhang-liao', type: '君臣 · 五子良将' },
  { from: 'cao-cao', to: 'yue-jin', type: '君臣 · 五子良将' },
  { from: 'cao-cao', to: 'yu-jin', type: '君臣 · 五子良将' },
  { from: 'cao-cao', to: 'zhang-he', type: '君臣 · 五子良将' },
  { from: 'cao-cao', to: 'xu-huang', type: '君臣 · 五子良将' },
  { from: 'cao-cao', to: 'dian-wei', type: '亲卫 · 救命' },
  { from: 'cao-cao', to: 'xu-chu', type: '亲卫 · 虎痴' },
  { from: 'cao-cao', to: 'lv-bu', type: '对手 · 濮阳/下邳' },
  { from: 'xun-yu', to: 'xun-you', type: '同族 · 叔侄' },
  { from: 'xun-yu', to: 'guo-jia', type: '同僚' },
  { from: 'guo-jia', to: 'jia-xu', type: '同僚' },
  { from: 'sima-yi', to: 'cao-shuang', type: '政敌 · 高平陵' },
  { from: 'cao-pi', to: 'cao-zhi', type: '兄弟 · 争储' },
  { from: 'cao-pi', to: 'zhen-furen', type: '夫妻 · 赐死' },
  { from: 'deng-ai', to: 'zhong-hui', type: '同僚 · 灭蜀内斗' },
  { from: 'deng-ai', to: 'jiang-wei', type: '对手 · 灭蜀' },
  { from: 'sun-jian', to: 'sun-ce', type: '父子 · 继承' },
  { from: 'sun-jian', to: 'sun-quan', type: '父子 · 继承' },
  { from: 'sun-ce', to: 'sun-quan', type: '兄弟 · 托付' },
  { from: 'sun-ce', to: 'zhou-yu', type: '总角之交 · 君臣' },
  { from: 'sun-quan', to: 'zhou-yu', type: '君臣 · 赤壁' },
  { from: 'sun-quan', to: 'lu-su', type: '君臣 · 榻上策' },
  { from: 'sun-quan', to: 'lv-meng', type: '君臣 · 士别三日' },
  { from: 'sun-quan', to: 'lu-xun', type: '君臣 · 夷陵' },
  { from: 'sun-quan', to: 'zhang-zhao', type: '托孤 · 直臣' },
  { from: 'sun-quan', to: 'zhuge-jin', type: '君臣 · 重臣' },
  { from: 'sun-quan', to: 'gu-yong', type: '君臣 · 丞相' },
  { from: 'sun-quan', to: 'cao-cao', type: '称臣 · 对手' },
  { from: 'zhou-yu', to: 'lu-su', type: '同僚 · 继任' },
  { from: 'lu-su', to: 'lv-meng', type: '同僚 · 继任' },
  { from: 'lv-meng', to: 'lu-xun', type: '同僚 · 继任' },
  { from: 'sun-ce', to: 'taishi-ci', type: '收降 · 信义' },
  { from: 'sun-quan', to: 'gan-ning', type: '君臣 · 锦帆' },
  { from: 'sun-quan', to: 'zhou-tai', type: '护卫 · 救命' },
  { from: 'sun-quan', to: 'ling-tong', type: '护卫 · 逍遥津' },
  { from: 'lu-xun', to: 'lu-kang', type: '父子 · 继任' },
  { from: 'zhuge-jin', to: 'zhuge-ke', type: '父子' },
  { from: 'zhuge-jin', to: 'zhuge-liang', type: '兄弟 · 各仕一方' },
  { from: 'dong-zhuo', to: 'lv-bu', type: '义父子 · 部下' },
  { from: 'lv-bu', to: 'diaochan', type: '演义 · 情侣' },
  { from: 'wang-yun', to: 'diaochan', type: '义父女 · 连环计' },
  { from: 'wang-yun', to: 'dong-zhuo', type: '政敌 · 除董卓' },
  { from: 'yuan-shao', to: 'yuan-shu', type: '兄弟 · 不和' },
  { from: 'yuan-shao', to: 'cao-cao', type: '旧友 · 官渡对手' },
  { from: 'yuan-shao', to: 'tian-feng', type: '谋主 · 冤杀' },
  { from: 'yuan-shao', to: 'ju-shou', type: '谋主 · 不用' },
  { from: 'yuan-shao', to: 'shen-pei', type: '谋臣 · 忠臣' },
  { from: 'liu-biao', to: 'liu-bei', type: '同宗 · 收留' },
  { from: 'liu-yan', to: 'liu-zhang', type: '父子 · 益州' },
  { from: 'gongsun-zan', to: 'liu-bei', type: '同窗 · 旧友' },
  { from: 'sima-hui', to: 'zhuge-liang', type: '赏识 · 水镜荐才' },
  { from: 'sima-hui', to: 'pang-tong', type: '赏识 · 水镜荐才' },
  { from: 'pang-degong', to: 'pang-tong', type: '叔侄 · 赏识' },
  { from: 'hua-tuo', to: 'cao-cao', type: '医患 · 猜忌' },
  { from: 'zhang-xiu', to: 'cao-cao', type: '宛城 · 降而复叛' },
  { from: 'gongsun-zan', to: 'zhao-yun', type: '旧主 · 未得重用' },
  { from: 'cao-rui', to: 'cao-pi', type: '父子 · 继位' },
  { from: 'cao-rui', to: 'sima-yi', type: '托孤 · 君臣' },
  { from: 'cao-fang', to: 'cao-rui', type: '养父子 · 继位' },
  { from: 'cao-fang', to: 'sima-shi', type: '被废 · 权臣' },
  { from: 'cao-mao', to: 'cao-fang', type: '继位' },
  { from: 'cao-mao', to: 'sima-zhao', type: '司马昭之心 · 被杀' },
  { from: 'cao-huan', to: 'cao-mao', type: '继位' },
  { from: 'cao-huan', to: 'sima-zhao', type: '禅位 · 曹魏亡' },
  { from: 'cao-ren', to: 'cao-cao', type: '从弟 · 宗亲名将' },
  { from: 'cao-hong', to: 'cao-cao', type: '从弟 · 宗亲名将' },
  { from: 'cao-chun', to: 'cao-cao', type: '从弟 · 虎豹骑统领' },
  { from: 'cao-xiu', to: 'cao-cao', type: '族子 · 宗室名将' },
  { from: 'cao-zhen', to: 'cao-cao', type: '族子 · 宗室名将' },
  { from: 'cao-zhang', to: 'cao-cao', type: '父子' },
  { from: 'cao-chong', to: 'cao-cao', type: '父子' },
  { from: 'xiahou-dun', to: 'cao-cao', type: '族亲 · 心腹大将' },
  { from: 'xiahou-yuan', to: 'cao-cao', type: '族亲 · 心腹大将' },
  { from: 'xiahou-shang', to: 'xiahou-yuan', type: '从子 · 宗亲将领' },
  { from: 'xiahou-ba', to: 'xiahou-yuan', type: '父子' },
  { from: 'pang-de', to: 'ma-teng', type: '故主 · 旧部' },
  { from: 'pang-de', to: 'cao-cao', type: '降将 · 魏将' },
  { from: 'wen-pin', to: 'liu-biao', type: '故主 · 旧部' },
  { from: 'wen-pin', to: 'cao-cao', type: '降将 · 江夏太守' },
  { from: 'li-dian', to: 'cao-cao', type: '魏将 · 合肥之战' },
  { from: 'zang-ba', to: 'cao-cao', type: '青徐豪帅 · 归魏' },
  { from: 'guo-huai', to: 'xiahou-yuan', type: '旧部 · 西线宿将' },
  { from: 'guo-huai', to: 'sima-yi', type: '西线同僚 · 抗蜀' },
  { from: 'hao-zhao', to: 'cao-zhen', type: '部将 · 陈仓之战' },
  { from: 'wang-ji', to: 'sima-yi', type: '魏将 · 司马氏部属' },
  { from: 'chen-tai', to: 'chen-qun', type: '父子' },
  { from: 'guanqiu-jian', to: 'sima-shi', type: '淮南三叛 · 被平' },
  { from: 'wang-ling', to: 'sima-yi', type: '淮南三叛 · 被擒' },
  { from: 'zhuge-dan', to: 'sima-zhao', type: '淮南三叛 · 被围' },
  { from: 'wen-yang', to: 'sima-shi', type: '乐嘉夜袭 · 勇猛' },
  { from: 'sima-shi', to: 'sima-yi', type: '父子' },
  { from: 'sima-zhao', to: 'sima-yi', type: '父子' },
  { from: 'jiang-ji', to: 'cao-cao', type: '魏臣 · 四朝元老' },
  { from: 'dong-zhao', to: 'cao-cao', type: '魏臣 · 劝进九锡' },
  { from: 'jia-kui', to: 'cao-cao', type: '魏臣 · 豫州刺史' },
  { from: 'liu-fang', to: 'cao-rui', type: '近臣 · 托孤' },
  { from: 'sun-zi', to: 'cao-rui', type: '近臣 · 托孤' },
  { from: 'wei-guan', to: 'sima-zhao', type: '魏末晋初重臣 · 灭蜀' },
  { from: 'zhong-yao', to: 'cao-cao', type: '魏臣 · 书法家' },
  { from: 'chen-qun', to: 'cao-cao', type: '魏臣 · 九品中正制' },
  { from: 'chen-qun', to: 'cao-pi', type: '君臣 · 九品中正制' },
  { from: 'hua-xin', to: 'cao-cao', type: '降臣 · 魏臣' },
  { from: 'wang-lang', to: 'cao-cao', type: '魏臣 · 经学家' },
  { from: 'man-chong', to: 'cao-cao', type: '魏臣 · 执法严明' },
  { from: 'yang-xiu', to: 'cao-zhi', type: '曹植谋主 · 夺嫡' },
  { from: 'yang-xiu', to: 'cao-cao', type: '主簿 · 被诛' },
  { from: 'cui-yan', to: 'cao-cao', type: '魏臣 · 刚正' },
  { from: 'mao-jie', to: 'cao-cao', type: '魏臣 · 主持选举' },
  { from: 'wang-can', to: 'cao-cao', type: '建安七子 · 魏臣' },
  { from: 'chen-lin', to: 'cao-cao', type: '建安七子 · 魏臣' },
  { from: 'ruan-yu', to: 'cao-cao', type: '建安七子 · 书记' },
  { from: 'xu-gan', to: 'cao-cao', type: '建安七子 · 魏臣' },
  { from: 'ying-yang', to: 'cao-cao', type: '建安七子 · 魏臣' },
  { from: 'liu-zhen', to: 'cao-cao', type: '建安七子 · 魏臣' },
  { from: 'du-ji', to: 'cao-cao', type: '魏臣 · 河东太守' },
  { from: 'zhang-ji', to: 'cao-cao', type: '魏臣 · 雍凉安边' },
  { from: 'gao-rou', to: 'cao-cao', type: '魏臣 · 廷尉' },
  { from: 'chen-jiao', to: 'cao-cao', type: '魏臣 · 尚书令' },
  { from: 'bian-furen', to: 'cao-cao', type: '夫妻 · 武宣卞皇后' },
  { from: 'guo-zhao', to: 'cao-pi', type: '夫妻 · 文德郭皇后' },
  { from: 'xin-xianying', to: 'guo-zhao', type: '同时代 · 魏宫智女' },
  { from: 'wang-yi', to: 'ma-chao', type: '对手 · 冀城之围' },
  { from: 'guan-lu', to: 'cao-rui', type: '方士 · 魏臣' },
  { from: 'he-yan', to: 'cao-shuang', type: '同党 · 玄学名士' },
  { from: 'he-yan', to: 'sima-yi', type: '政敌 · 被诛' },
  { from: 'wang-bi', to: 'he-yan', type: '玄学同好' },
  { from: 'ji-kang', to: 'ruan-ji', type: '竹林七贤' },
  { from: 'ji-kang', to: 'sima-zhao', type: '政敌 · 被杀' },
  { from: 'ruan-ji', to: 'sima-zhao', type: '被迫出仕 · 避世' },
  { from: 'liu-shan', to: 'liu-bei', type: '父子 · 继位' },
  { from: 'liu-shan', to: 'zhuge-liang', type: '托孤 · 相父' },
  { from: 'liu-chen', to: 'liu-shan', type: '父子 · 殉国' },
  { from: 'liu-feng', to: 'liu-bei', type: '养父子' },
  { from: 'liu-li', to: 'liu-bei', type: '父子 · 蜀汉宗室' },
  { from: 'liu-yong', to: 'liu-bei', type: '父子 · 蜀汉宗室' },
  { from: 'wu-yi', to: 'liu-bei', type: '外戚 · 蜀将' },
  { from: 'wu-ban', to: 'liu-bei', type: '外戚 · 蜀将' },
  { from: 'wang-ping', to: 'zhuge-liang', type: '蜀将 · 街亭无过' },
  { from: 'liao-hua', to: 'guan-yu', type: '旧部 · 随关羽' },
  { from: 'liao-hua', to: 'liu-bei', type: '蜀汉宿将' },
  { from: 'zhang-yi', to: 'jiang-wei', type: '姜维部将' },
  { from: 'zhang-ni', to: 'jiang-wei', type: '姜维部将 · 南中' },
  { from: 'chen-dao', to: 'liu-bei', type: '亲卫 · 白毦兵' },
  { from: 'xiang-chong', to: 'zhuge-liang', type: '出师表举荐' },
  { from: 'fu-qian', to: 'jiang-wei', type: '姜维部将 · 殉国' },
  { from: 'huo-jun', to: 'liu-bei', type: '蜀将 · 守葭萌关' },
  { from: 'luo-xian', to: 'liu-shan', type: '蜀将 · 永安守城' },
  { from: 'meng-huo', to: 'zhuge-liang', type: '七擒七纵 · 归心' },
  { from: 'guan-ping', to: 'guan-yu', type: '父子' },
  { from: 'guan-xing', to: 'guan-yu', type: '父子' },
  { from: 'feng-xi', to: 'liu-bei', type: '蜀将 · 夷陵战死' },
  { from: 'zhang-nan', to: 'liu-bei', type: '蜀将 · 夷陵战死' },
  { from: 'huang-quan', to: 'liu-bei', type: '谋臣 · 后降魏' },
  { from: 'li-hui', to: 'zhuge-liang', type: '南中 · 庲降都督' },
  { from: 'deng-zhi', to: 'zhuge-liang', type: '出使东吴 · 重修盟好' },
  { from: 'ma-liang', to: 'liu-bei', type: '幕僚 · 马氏五常' },
  { from: 'zhang-shao', to: 'liu-shan', type: '蜀臣 · 降魏' },
  { from: 'guo-youzhi', to: 'zhuge-liang', type: '出师表 · 侍中' },
  { from: 'yi-ji', to: 'liu-bei', type: '蜀汉文臣 · 蜀科' },
  { from: 'qin-mi', to: 'liu-bei', type: '蜀汉文臣 · 善辩' },
  { from: 'qiao-zhou', to: 'liu-shan', type: '学者 · 劝降' },
  { from: 'xi-zheng', to: 'liu-shan', type: '蜀臣 · 随主入魏' },
  { from: 'li-yan', to: 'liu-bei', type: '托孤大臣' },
  { from: 'li-yan', to: 'zhuge-liang', type: '政敌 · 被废' },
  { from: 'chen-zhen', to: 'liu-bei', type: '蜀汉文臣 · 外交' },
  { from: 'liu-ba', to: 'liu-bei', type: '蜀汉文臣 · 理财' },
  { from: 'xiang-lang', to: 'zhuge-liang', type: '蜀汉文臣 · 治学' },
  { from: 'gan-furen', to: 'liu-bei', type: '夫妻 · 刘禅生母' },
  { from: 'mi-furen', to: 'liu-bei', type: '夫妻 · 长坂坡' },
  { from: 'huang-yueying', to: 'zhuge-liang', type: '夫妻 · 才女' },
  { from: 'zhurong-furen', to: 'meng-huo', type: '夫妻 · 南中女将' },
  { from: 'guan-yinping', to: 'guan-yu', type: '父女 · 民间传说' },
  { from: 'zhou-qun', to: 'liu-bei', type: '蜀汉方士 · 占候' },
  { from: 'du-wei', to: 'zhuge-liang', type: '隐士 · 礼请出仕' },
  { from: 'zhang-yu', to: 'liu-bei', type: '蜀汉方士 · 因言被杀' },
  { from: 'sun-liang', to: 'sun-quan', type: '父子 · 继位' },
  { from: 'sun-xiu', to: 'sun-quan', type: '父子 · 继位' },
  { from: 'sun-xiu', to: 'sun-chen', type: '除权臣 · 孙綝' },
  { from: 'sun-hao', to: 'sun-xiu', type: '继位 · 暴君' },
  { from: 'sun-jing', to: 'sun-jian', type: '兄弟 · 孙氏宗室' },
  { from: 'sun-ben', to: 'sun-jian', type: '宗亲 · 孙氏将领' },
  { from: 'sun-fu', to: 'sun-ben', type: '兄弟 · 孙氏宗室' },
  { from: 'sun-jiao', to: 'sun-quan', type: '宗室 · 东吴将领' },
  { from: 'sun-huan', to: 'sun-quan', type: '宗室 · 夷陵之战' },
  { from: 'sun-jun', to: 'zhuge-ke', type: '政敌 · 诛杀诸葛恪' },
  { from: 'sun-jun', to: 'sun-liang', type: '权臣 · 废立' },
  { from: 'sun-chen', to: 'sun-jun', type: '从弟 · 权臣' },
  { from: 'sun-chen', to: 'sun-liang', type: '权臣 · 废黜孙亮' },
  { from: 'sun-he', to: 'sun-quan', type: '父子 · 太子' },
  { from: 'sun-ba', to: 'sun-quan', type: '父子 · 鲁王' },
  { from: 'sun-deng', to: 'sun-quan', type: '父子 · 太子' },
  { from: 'sun-shao', to: 'sun-quan', type: '宗亲 · 镇守京口' },
  { from: 'cheng-pu', to: 'sun-jian', type: '旧将 · 三朝元老' },
  { from: 'huang-gai', to: 'sun-jian', type: '旧将 · 赤壁火攻' },
  { from: 'han-dang', to: 'sun-jian', type: '旧将 · 水战' },
  { from: 'jiang-qin', to: 'sun-quan', type: '东吴将领 · 水军' },
  { from: 'chen-wu', to: 'sun-quan', type: '东吴猛将 · 合肥战死' },
  { from: 'dong-xi', to: 'sun-quan', type: '东吴猛将 · 濡须口' },
  { from: 'xu-sheng', to: 'sun-quan', type: '东吴名将 · 疑城退曹丕' },
  { from: 'pan-zhang', to: 'sun-quan', type: '东吴将领 · 擒关羽' },
  { from: 'ding-feng', to: 'sun-quan', type: '东吴后期名将 · 四朝元老' },
  { from: 'zhu-ran', to: 'sun-quan', type: '东吴名将 · 江陵守城' },
  { from: 'zhu-huan', to: 'sun-quan', type: '东吴名将 · 濡须口' },
  { from: 'quan-cong', to: 'sun-quan', type: '东吴名将 · 孙权女婿' },
  { from: 'lv-fan', to: 'sun-ce', type: '孙吴元老 · 心腹' },
  { from: 'he-qi', to: 'sun-quan', type: '东吴名将 · 平山越' },
  { from: 'liu-zan', to: 'sun-quan', type: '东吴后期老将' },
  { from: 'wu-yan', to: 'sun-hao', type: '东吴后期将领 · 铁锁横江' },
  { from: 'zhang-hong', to: 'sun-ce', type: '谋臣 · 二张' },
  { from: 'xue-zong', to: 'sun-quan', type: '东吴名儒 · 外交' },
  { from: 'lu-ji', to: 'sun-quan', type: '东吴学者 · 怀橘遗亲' },
  { from: 'bu-zhi', to: 'sun-quan', type: '丞相 · 平交州' },
  { from: 'yu-fan', to: 'sun-quan', type: '狂直 · 被流放' },
  { from: 'yan-jun', to: 'sun-quan', type: '东吴名儒 · 文臣' },
  { from: 'cheng-bing', to: 'sun-quan', type: '东吴名儒 · 经学' },
  { from: 'kan-ze', to: 'sun-quan', type: '东吴学者 · 文臣' },
  { from: 'wei-zhao', to: 'sun-hao', type: '史官 · 被孙皓杀' },
  { from: 'hua-he', to: 'sun-hao', type: '东吴后期 · 直谏' },
  { from: 'pu-yangxing', to: 'sun-xiu', type: '丞相 · 拥立孙休' },
  { from: 'zhang-ti', to: 'sun-hao', type: '丞相 · 殉国' },
  { from: 'zhao-zi', to: 'sun-quan', type: '外交 · 出使曹魏' },
  { from: 'da-qiao', to: 'sun-ce', type: '夫妻 · 江东二乔' },
  { from: 'xiao-qiao', to: 'zhou-yu', type: '夫妻 · 江东二乔' },
  { from: 'sun-shangxiang', to: 'sun-quan', type: '兄妹 · 弓腰姬' },
  { from: 'sun-shangxiang', to: 'liu-bei', type: '夫妻 · 孙刘联姻' },
  { from: 'wu-guotai', to: 'sun-jian', type: '夫妻 · 孙坚夫人' },
  { from: 'bu-lianshi', to: 'sun-quan', type: '夫妻 · 追封皇后' },
  { from: 'sun-luban', to: 'sun-quan', type: '父女 · 二宫之争' },
  { from: 'zhao-da', to: 'sun-quan', type: '东吴方士 · 术数' },
  { from: 'liu-dun', to: 'sun-quan', type: '东吴方士 · 天象' },
  { from: 'wu-fan', to: 'sun-quan', type: '东吴方士 · 预言' },
  { from: 'liu-xie', to: 'dong-zhuo', type: '汉帝 · 权臣' },
  { from: 'liu-xie', to: 'cao-cao', type: '汉帝 · 挟天子' },
  { from: 'liu-bian', to: 'he-taihou', type: '母子 · 汉少帝' },
  { from: 'liu-bian', to: 'dong-zhuo', type: '被废 · 遇害' },
  { from: 'ma-teng', to: 'ma-chao', type: '父子 · 西凉' },
  { from: 'ma-teng', to: 'han-sui', type: '西凉军阀 · 盟友' },
  { from: 'han-sui', to: 'ma-chao', type: '叔父辈 · 渭水联军' },
  { from: 'tao-qian', to: 'liu-bei', type: '让徐州 · 故主' },
  { from: 'zhang-lu', to: 'liu-zhang', type: '汉中 · 对峙' },
  { from: 'gongsun-du', to: 'cao-cao', type: '辽东太守 · 受封' },
  { from: 'shi-xie', to: 'sun-quan', type: '交州太守 · 归附东吴' },
  { from: 'hua-xiong', to: 'dong-zhuo', type: '部将 · 温酒斩华雄' },
  { from: 'yan-liang', to: 'yuan-shao', type: '部将 · 白马之战' },
  { from: 'wen-chou', to: 'yuan-shao', type: '部将 · 延津之战' },
  { from: 'gao-shun', to: 'lv-bu', type: '部将 · 陷阵营' },
  { from: 'xu-rong', to: 'dong-zhuo', type: '部将 · 击败曹操孙坚' },
  { from: 'qu-yi', to: 'yuan-shao', type: '部将 · 界桥先登' },
  { from: 'ji-ling', to: 'yuan-shu', type: '部将 · 辕门射戟' },
  { from: 'huang-zu', to: 'liu-biao', type: '部将 · 江夏太守' },
  { from: 'zang-hong', to: 'yuan-shao', type: '旧部 · 反目' },
  { from: 'li-jue', to: 'dong-zhuo', type: '旧部 · 把持朝政' },
  { from: 'guo-si', to: 'dong-zhuo', type: '旧部 · 把持朝政' },
  { from: 'zhang-ji-qun', to: 'dong-zhuo', type: '旧部 · 宛城' },
  { from: 'fan-chou', to: 'dong-zhuo', type: '旧部 · 西凉' },
  { from: 'niu-fu', to: 'dong-zhuo', type: '女婿 · 部将' },
  { from: 'chen-gong', to: 'lv-bu', type: '谋主 · 宁死不降' },
  { from: 'chen-gong', to: 'cao-cao', type: '旧交 · 捉放曹' },
  { from: 'li-ru', to: 'dong-zhuo', type: '谋主 · 毒计' },
  { from: 'xu-you', to: 'yuan-shao', type: '故主 · 官渡反水' },
  { from: 'xu-you', to: 'cao-cao', type: '火烧乌巢 · 后被杀' },
  { from: 'guo-tu', to: 'yuan-shao', type: '谋臣 · 谗言' },
  { from: 'feng-ji', to: 'yuan-shao', type: '谋臣 · 与审配不和' },
  { from: 'xun-chen', to: 'yuan-shao', type: '谋臣 · 说韩馥让冀州' },
  { from: 'kuai-liang', to: 'liu-biao', type: '谋臣 · 荆州' },
  { from: 'kuai-yue', to: 'liu-biao', type: '谋臣 · 后归曹操' },
  { from: 'yan-pu', to: 'zhang-lu', type: '谋臣 · 劝降' },
  { from: 'zhang-song', to: 'liu-zhang', type: '别驾 · 献西川地图' },
  { from: 'zhang-song', to: 'liu-bei', type: '内应 · 助取益州' },
  { from: 'chen-deng', to: 'liu-bei', type: '徐州旧交 · 助刘备' },
  { from: 'chen-deng', to: 'cao-cao', type: '助曹操 · 破吕布' },
  { from: 'chen-gui', to: 'cao-cao', type: '徐州士族 · 暗助曹操' },
  { from: 'cai-yong', to: 'dong-zhuo', type: '被强征 · 名士' },
  { from: 'cai-yong', to: 'cai-wenji', type: '父女' },
  { from: 'kong-rong', to: 'cao-cao', type: '政敌 · 被杀' },
  { from: 'kong-rong', to: 'liu-bei', type: '旧交 · 孔融让梨' },
  { from: 'mi-heng', to: 'kong-rong', type: '好友 · 荐举' },
  { from: 'mi-heng', to: 'huang-zu', type: '狂士 · 被黄祖杀' },
  { from: 'liu-fu', to: 'cao-cao', type: '扬州刺史 · 兴水利' },
  { from: 'xu-jing', to: 'liu-bei', type: '名士 · 后仕蜀汉' },
  { from: 'han-song', to: 'liu-biao', type: '臣属 · 后归曹操' },
  { from: 'fu-xun', to: 'liu-biao', type: '臣属 · 劝刘琮降曹' },
  { from: 'wang-lei', to: 'liu-zhang', type: '死谏 · 阻止刘备入蜀' },
  { from: 'zou-furen', to: 'zhang-ji-qun', type: '夫妻 · 宛城之战' },
  { from: 'dong-bai', to: 'dong-zhuo', type: '祖孙女 · 董卓孙女' },
  { from: 'tang-ji', to: 'liu-bian', type: '夫妻 · 汉少帝妃' },
  { from: 'zhang-zhongjing', to: 'hua-tuo', type: '同时代名医 · 医圣与神医' },
  { from: 'zuo-ci', to: 'cao-cao', type: '方士 · 戏曹操' },
  { from: 'yu-ji', to: 'sun-ce', type: '道士 · 被孙策杀' },
  { from: 'xu-shao', to: 'cao-cao', type: '月旦评 · 识曹操' },
  { from: 'huang-chengyan', to: 'zhuge-liang', type: '岳父 · 荆州名士' },

]

/** Pair key used to de-duplicate undirected relations. */
function pairKey(a: string, b: string): string {
  return a < b ? `${a}::${b}` : `${b}::${a}`
}

/**
 * Build confirmed edge entries for the framework. Labels are carried on the
 * edge so the detail panel can say what the connection means.
 */
export function generateSanguoEdges(): SanguoEdge[] {
  const seen = new Set<string>()
  const out: SanguoEdge[] = []
  for (const r of RELATIONS) {
    if (r.from === r.to) continue
    const key = pairKey(r.from, r.to)
    if (seen.has(key)) continue
    seen.add(key)
    const label = r.note ? `${r.type} · ${r.note}` : r.type
    out.push({
      id: `rel:${key}`,
      from: r.from,
      to: r.to,
      createdAt: 0,
      label,
    })
  }
  return out
}
